### ISSUE TITLE
npm install 후 start 시에 화면이 뜨지 않는 현상

### ISSUE THREAD

**Issue by k-young-passionate** [siisee11/beljaby#2]
/beljaby directory에서 필요한 npm package를 npm install로 전부 설치 후
npm start 로 실행을 시켰지만 페이지에 아무것도 뜨지 않습니다.

건드린 설정
1. package-lock.json이 darwin 에 맞춰져있어 삭제하고 재생성하였습니다.
2. watch 갯수 제한이 있어 OS 자체의 max_user_watches 를 임시로 524288 개로 설정했습니다.

OS: Ubuntu 18.04.5 LTS
node version: v14.15.4
npm version: 6.14.11

![스크린샷, 2021-01-16 23-38-30](https://user-images.githubusercontent.com/11757075/104814785-fd4ace00-5853-11eb-8a1a-3838d8a6a9aa.png)

**Comment by siisee11** [comment]
어떻게 바꾸면 되나요? PR 보내주실수있나요

**Comment by k-young-passionate** [comment]
@siisee11 
api key가 환경변수에 설정되어있지 않아 google oauth, riot image 등을 불러오지 못하는 것 같습니다.

혹시 사용되는 api들에 대해서 필요한 api key들과 설정 방법을 알려주실 수 있나요?

**Comment by siisee11** [comment]
아 맞아요. 혹시 실무에서는 API key 공유를 어떻게 하는지 아시나요??
.env 파일을 만들어야되는데 따로보내드릴게요

**Comment by k-young-passionate** [comment]
> 아 맞아요. 혹시 실무에서는 API key 공유를 어떻게 하는지 아시나요??
> .env 파일을 만들어야되는데 따로보내드릴게요

정확히는 모르지만, local 환경에서는 단위 test가 가능하게 하거나 mockup data를 이용해 test해보고, api key가 필요한 경우에는 test 서버에서 test를 해보는 것으로 들은 것 같습니다. 어차피 개인프로젝트라서 필요한 api key가 어떤 것이 있는지, 어떻게 설정하는지 정도 만들어놓으면 알아서 하지 않을까 싶어요.

**Comment by k-young-passionate** [comment]
보내주신 파일로 잘 돌아가는 것 확인했습니다 :+1: 

/home/keonyoung/사진/스크린샷, 2021-01-17 00-16-36.png

**Comment by siisee11** [comment]
감사합니다. 문서화 잘 시켜 놓겠습니다 :)
